version: '3'

services:
   db:
     image: mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root

   gate:
     depends_on:
       - db
     image: gate
     volumes:
       - gate:/opt/gate-code/
     ports:
       - 8080:8080
     restart: always
     environment:
       SQLHOST: db
       PASSWORD: root
       HOST: "${HOST}"
volumes:
      db_data:
      gate:

